### ISSUE TITLE
Is it safe to store logged-in user data in cookie?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [ahadyekta/nuxt-auth-external-jwt#1]
Beside access token, i would also like to store user info examples: user_id, role, name, email... (and access_token) because i do not want to fetch for these data every time user access the website. Like i would like to show logged-in user's name in Navbar for every pages.

Is it safe to store these data in cookie?

Please suggest.

Thanks.

**Comment by ahadyekta** [comment]
There are some good answers to your question. 
https://stackoverflow.com/questions/706858/what-information-is-ok-to-store-in-cookies
