### ISSUE TITLE
 Cannot read property 'headers' of undefined in npm run generate

### ISSUE THREAD

**Issue by canmehmetjs** [ahadyekta/nuxt-auth-external-jwt#2]
I just cloned your repo , npm install and run npm run generate. 

I'm getting this error : 

TypeError: Cannot read property 'headers' of undefined
  
  - server-bundle.js:3648 Store.nuxtServerInit
    server-bundle.js:3648:17
  
  - vuex.common.js:706 Array.wrappedActionHandler
    [nuxt-auth-external-jwt]/[vuex]/dist/vuex.common.js:706:23
  
  - vuex.common.js:428 Store.dispatch
    [nuxt-auth-external-jwt]/[vuex]/dist/vuex.common.js:428:15
  
  - vuex.common.js:334 Store.boundDispatch [as dispatch]
    [nuxt-auth-external-jwt]/[vuex]/dist/vuex.common.js:334:21
  
  - server-bundle.js:1327 module.exports.__webpack_exports__.default
    server-bundle.js:1327:19
  
  - next_tick.js:178 process._tickCallback
    internal/process/next_tick.js:178:7
  
Is there a solution to this ?

**Comment by ahadyekta** [comment]
I think because of using nuxtServerInit , you cannot run generate command on this repository to convert it to a static HTML.
